# Generated by Django 3.2.13 on 2022-06-02 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20220522_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['position']},
        ),
    ]
